### ISSUE TITLE
partly downloaded isos crash program

### ISSUE THREAD

**Issue by rminnich** [u-root/webboot#144]
**Describe the bug**
if you power cycle the system in the middle of a download, and try to use that iso, webboot will crash

**To Reproduce**
start a download
power cycle the laptop in the middle of the download
try to use the partly downloaded ISO
webboot crashes

**Expected behavior**
I will not see that ISO on next boot b/c it is corrupt

**Comment by xsy1996** [comment]
I was thinking about adding a resumable upload function to webboot. And I think this issue can be solved together with this function. As long as we add a log to record the download progress of the downloaded iso, the log can be a simple json file or txt file. Save the file address and the corresponding progress, if it is completed, the progress is "done", if not, the progress is "xx" (the number of bytes downloaded). The code of updating the log can be placed where the progress bar is updated, because the progress bar is updated according to the number of bytes that have been downloaded. And look at the log to check the download progress of the file before adding an iso to the menu. If the download is not completed,  do no add it to the menu.

**Comment by GBA-17** [comment]
With the new error handler, this case will bring up the error message box, and then return to the main menu.

Maybe we can add a menu that asks if they would like to delete the iso?
