### ISSUE TITLE
error handling needs rework

### ISSUE THREAD

**Issue by rminnich** [u-root/webboot#155]
**Describe the bug**
Right now, on an error, webboot exits without displaying most of the information.

**To Reproduce**
just try to download or boot anything with failure. The program exits with little information.

**Expected behavior**
We get all the error text displayed in a box, and the option of exiting or trying again from the boot menu.

**Additional context**

**Comment by xsy1996** [comment]
I read the PR # 154 and I am not really understand.. why we do not use menu.DisplayResult to display the error message?

I mean,is that ok if we use menu.DisplayResult to dispaly the error, and then go back to the upper menu just act the same as we hit the back opion. menu.DisplayResul will display the error in a box just as the expected behavior

for example when download option is error, we ca ndo like this:

case *DownloadOption:
if entry, err = entry.(*DownloadOption).exec(ui.PollEvents(), *network, cacheDir); err != nil {
menu.DisplayResult([]string{fmt.Sprintf("Download option failed:%v (%s)", err, l.String())}, ui.PollEvents())
entry = &BackOprion{}
}
if _, ok := entry.(*BackOption); ok {
entry = getMainMenu(cacheDir)
}

dose that work?
